package main

const terrTableCreationQuery = `CREATE TABLE territories
(
		code text NOT NULL UNIQUE,
		name text,
		timezone text,
		gallery text,
		flag text,
		map text,
		main_language text,
		gdp text,
		literacy_pct real,
		population int,
		demographic_profile text,
		railways text,
		background text,
		location text,
		geographic_coordinates text,
		map_references text,
		area text,
		area_comparative text,
		land_boundaries text,
		coastline text,
		maritime_claims text,
		climate text,
		terrain text,
		elevation text,
		natural_resources text,
		land_use text,
		irrigated_land text,
		total_renewable_water_resources text,
		population_distribution text,
		natural_hazards text,
		environment_international_agreements text,
		geography_note text,
		nationality text,
		ethnic_groups text,
		languages text,
		religions text,
		age_structure text,
		dependency_ratios text,
		median_age text,
		population_growth_rate text,
		birth_rate text,
		death_rate text,
		net_migration_rate text,
		urbanization text,
		major_urban_areas_population text,
		sex_ratio text,
		mothers_mean_age_at_first_birth text,
		maternal_mortality_rate text,
		infant_mortality_rate text,
		life_expectancy_at_birth text,
		total_fertility_rate text,
		contraceptive_prevalence_rate text,
		drinking_water_source text,
		current_health_expenditure text,
		physicians_density text,
		hospital_bed_density text,
		sanitation_facility_access text,
		hiv_aids_adult_prevalence_rate text,
		hiv_aids_people_living_with_hiv_aids text,
		hiv_aids_deaths text,
		major_infectious_diseases text,
		obesity_adult_prevalence_rate text,
		children_under_the_age_of__years_underweight text,
		education_expenditures text,
		literacy text,
		school_life_expectancy_primary_to_tertiary_education text,
		unemployment_youth_ages_ text,
		environment_current_issues text,
		air_pollutants text,
		total_water_withdrawal text,
		revenue_from_forest_resources text,
		revenue_from_coal text,
		food_insecurity text,
		waste_and_recycling text,
		country_name text,
		government_type text,
		capital text,
		administrative_divisions text,
		independence text,
		national_holiday text,
		constitution text,
		legal_system text,
		international_law_organization_participation text,
		citizenship text,
		suffrage text,
		executive_branch text,
		legislative_branch text,
		judicial_branch text,
		political_parties_and_leaders text,
		international_organization_participation text,
		diplomatic_representation_in_the_us text,
		diplomatic_representation_from_the_us text,
		flag_description text,
		national_symbols text,
		national_anthem text,
		economic_overview text,
		real_gdp_growth_rate text,
		inflation_rate_consumer_prices text,
		real_gdp_purchasing_power_parity text,
		gdp_official_exchange_rate text,
		real_gdp_per_capita text,
		gross_national_saving text,
		gdp_composition_by_sector_of_origin text,
		gdp_composition_by_end_use text,
		ease_of_doing_business_index_scores text,
		agricultural_products text,
		industries text,
		industrial_production_growth_rate text,
		labor_force text,
		labor_force_by_occupation text,
		unemployment_rate text,
		population_below_poverty_line text,
		gini_index_coefficient_distribution_of_family_income text,
		household_income_or_consumption_by_percentage_share text,
		budget text,
		taxes_and_other_revenues text,
		budget_surplus__or_deficit_ text,
		public_debt text,
		fiscal_year text,
		current_account_balance text,
		exports text,
		exports_partners text,
		exports_commodities text,
		imports text,
		imports_partners text,
		imports_commodities text,
		reserves_of_foreign_exchange_and_gold text,
		debt_external text,
		exchange_rates text,
		electricity_access text,
		electricity_production text,
		electricity_consumption text,
		electricity_exports text,
		electricity_imports text,
		electricity_installed_generating_capacity text,
		electricity_from_fossil_fuels text,
		electricity_from_nuclear_fuels text,
		electricity_from_hydroelectric_plants text,
		electricity_from_other_renewable_sources text,
		crude_oil_production text,
		crude_oil_exports text,
		crude_oil_imports text,
		crude_oil_proved_reserves text,
		refined_petroleum_products_production text,
		refined_petroleum_products_consumption text,
		refined_petroleum_products_exports text,
		refined_petroleum_products_imports text,
		natural_gas_production text,
		natural_gas_consumption text,
		natural_gas_exports text,
		natural_gas_imports text,
		natural_gas_proved_reserves text,
		carbon_dioxide_emissions_from_consumption_of_energy text,
		telephones_fixed_lines text,
		telephones_mobile_cellular text,
		telecommunication_systems text,
		broadcast_media text,
		internet_country_code text,
		internet_users text,
		broadband_fixed_subscriptions text,
		national_air_transport_system text,
		civil_aircraft_registration_country_code_prefix text,
		airports text,
		airports_with_paved_runways text,
		airports_with_unpaved_runways text,
		heliports text,
		pipelines text,
		roadways text,
		waterways text,
		ports_and_terminals text,
		military_and_security_forces text,
		military_expenditures text,
		military_and_security_service_personnel_strengths text,
		military_equipment_inventories_and_acquisitions text,
		military_service_age_and_obligation text,
		military_note text,
		terrorist_groups text,
		disputes_international text,
		refugees_and_internally_displaced_persons text,
		illicit_drugs text,
		trafficking_in_persons text,
		CONSTRAINT territories_pkey PRIMARY KEY (code)
)`

const langTerrTableCreationQuery = `CREATE TABLE languageTerritory
(
		language_code text NOT NULL,
		territory_code	text	NOT NULL REFERENCES territories(code),
		population_pct	real,
		official_status	bool,
		CONSTRAINT language_territory_pkey PRIMARY KEY (language_code, territory_code)
)`

const langTableCreationQuery = `CREATE TABLE languages
(
		code text NOT NULL,
		name text NOT NULL,
		CONSTRAINT languages_pkey PRIMARY KEY (code)
)
`

const subTableCreationQuery = `CREATE TABLE subdivisions
(
		code text NOT NULL,
		name	text	NOT NULL,
		territory_code text NOT NULL,
		CONSTRAINT subdivisions_pkey PRIMARY KEY (code),
		CONSTRAINT subdivisions_fkey FOREIGN KEY (territory_code) REFERENCES territories(code)
)`
